import * as React from 'react';
import { Link } from 'react-router-dom';
import { Download } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { SortableTableHead } from '@/components/ui/sortable-table-head';
import { useSortableTable } from '@/lib/useSortableTable';
import { RecentActivityPanel } from '@/components/RecentActivityPanel';
import { useLogPageView } from '@/lib/activityLog';
import { MOCK_ACTIVITY_LOGS, MOCK_GENERATED_DOCUMENTS, type MockGeneratedDocument } from '@/lib/mockData';
import { formatDateTime } from '@/lib/utils';

function getSortValue(doc: MockGeneratedDocument, key: string): string | number | Date | null | undefined {
  switch (key) {
    case 'documentName':
      return doc.documentName;
    case 'documentType':
      return doc.documentType;
    case 'loanCode':
      return doc.loanCode;
    case 'borrowerName':
      return doc.borrowerName;
    case 'generatedBy':
      return doc.generatedBy;
    case 'generatedAt':
      return new Date(doc.generatedAt);
    default:
      return null;
  }
}

/**
 * Generated Documents — mock registry of the official documents produced when
 * a loan account is activated (Promissory Note, Disclosure Statement, Loan
 * Agreement, Amortization Schedule — matching the company's real legal
 * templates). Metadata only: file contents are not included in this preview,
 * so Download stays disabled.
 */
export function GeneratedDocumentsPage() {
  useLogPageView('Generated Documents');
  const [typeFilter, setTypeFilter] = React.useState<string>('ALL');
  const typeOptions = ['ALL', ...[...new Set(MOCK_GENERATED_DOCUMENTS.map((d) => d.documentType))].sort()];
  const filtered = MOCK_GENERATED_DOCUMENTS.filter((doc) => typeFilter === 'ALL' || doc.documentType === typeFilter);
  const { sorted, sort, toggleSort } = useSortableTable(filtered, getSortValue, { key: 'generatedAt', direction: 'desc' });

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-semibold tracking-tight">Generated Documents</h2>
        <p className="text-sm text-muted-foreground">
          Official documents generated when a loan account is activated. Mock registry — names and metadata only; downloads are
          disabled in this preview build.
        </p>
      </div>

      <div className="flex items-center gap-2">
        <Select value={typeFilter} onValueChange={setTypeFilter}>
          <SelectTrigger className="w-64">
            <SelectValue placeholder="Document type" />
          </SelectTrigger>
          <SelectContent>
            {typeOptions.map((type) => (
              <SelectItem key={type} value={type}>
                {type === 'ALL' ? 'All document types' : type}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        <p className="text-sm text-muted-foreground">
          {sorted.length} document{sorted.length === 1 ? '' : 's'}
        </p>
      </div>

      <Card>
        <CardContent className="p-0">
          <Table>
            <TableHeader>
              <TableRow>
                <SortableTableHead sortKey="documentName" currentSort={sort} onSort={toggleSort}>
                  Document
                </SortableTableHead>
                <SortableTableHead sortKey="documentType" currentSort={sort} onSort={toggleSort}>
                  Type
                </SortableTableHead>
                <SortableTableHead sortKey="loanCode" currentSort={sort} onSort={toggleSort}>
                  Loan Account
                </SortableTableHead>
                <SortableTableHead sortKey="borrowerName" currentSort={sort} onSort={toggleSort}>
                  Client
                </SortableTableHead>
                <SortableTableHead sortKey="generatedBy" currentSort={sort} onSort={toggleSort}>
                  Generated By
                </SortableTableHead>
                <SortableTableHead sortKey="generatedAt" currentSort={sort} onSort={toggleSort} isDateColumn>
                  Generated At
                </SortableTableHead>
                <TableHead />
              </TableRow>
            </TableHeader>
            <TableBody>
              {sorted.map((doc) => (
                <TableRow key={doc.id}>
                  <TableCell className="font-medium">{doc.documentName}</TableCell>
                  <TableCell className="text-muted-foreground">{doc.documentType}</TableCell>
                  <TableCell>
                    <Link to={`/loans/${doc.loanId}`} className="text-primary underline-offset-2 hover:underline">
                      {doc.loanCode}
                    </Link>
                  </TableCell>
                  <TableCell>{doc.borrowerName}</TableCell>
                  <TableCell className="text-muted-foreground">{doc.generatedBy}</TableCell>
                  <TableCell className="text-muted-foreground">{formatDateTime(doc.generatedAt)}</TableCell>
                  <TableCell className="text-right">
                    <Button variant="outline" size="sm" disabled title="Preview build — downloads disabled" className="gap-1.5">
                      <Download className="h-3.5 w-3.5" />
                      Download
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      <RecentActivityPanel
        entries={MOCK_ACTIVITY_LOGS.filter((l) => l.entityType === 'Generated Documents')}
        title="Recent Activity — Generated Documents"
      />
    </div>
  );
}
