-- CreateEnum
CREATE TYPE "AttachmentDocumentCategory" AS ENUM ('PROFILE_PICTURE', 'VALID_ID_BORROWER', 'VALID_ID_CO_BORROWER', 'PROOF_OF_BILLING', 'EMPLOYEE_ID', 'BUSINESS_CLEARANCE', 'CORPORATE_PAYSLIP', 'SEAMANS_BOOK', 'OVERSEAS_EMPLOYMENT_CERTIFICATE');

-- AlterTable
ALTER TABLE "attachments" ADD COLUMN     "documentCategory" "AttachmentDocumentCategory";
